<!-- filepath: c:\Users\gr97\OneDrive - University of St Andrews\Documents\teaching\EC5230-industrial-organisation\exercises\exercises-rmd\cournot-duopoly-welfare.Rmd -->
```{r, echo=FALSE}
# Parameters
a  <- 20
c1 <- 0
c2 <- 5

# Cournot duopoly equilibrium
q1 <- 25/3
q2 <- 10/3
Q  <- q1 + q2
P  <- a - Q

CS <- (1/2) * Q^2
PS <- q1^2 + q2^2
WL <- 200 - CS - PS
```

### Problem 1: Welfare analysis

Consider a market with inverse demand

$$
P = 20 - Q
$$

and three firms with cost functions $c_i(q_i) = c_i q_i$, where

$$
c_1 = 0,\quad c_2 = 5,\quad c_3 = 7.
$$

---

### Cournot duopoly

Compute the Nash equilibrium quantities in the Cournot duopoly between firm 1 and firm 2.

* Firm 1 equilibrium output: $q_1^D =$ ##{num}##
* Firm 2 equilibrium output: $q_2^D =$ ##{num}##

---

### Welfare components

Given your answer in (a), compute:

* Equilibrium price: $P^D =$ ##{num}##
* Consumer surplus: $CS^D =$ ##{num}##
* Producer surplus: $PS^D =$ ##{num}##
* Welfare loss: $WL^D =$ ##{num}##

---

### Comparison and policy intuition

Compare consumer surplus, producer surplus, and welfare loss to those under monopoly and Cournot triopoly.

Briefly describe where the duopoly outcomes lie relative to monopoly and triopoly:

##{string}##

---

## Meta-information

---
exname: cournot_duopoly_welfare
extype: cloze
expoints: 6
exsolution: 25/3|10/3|25/3|1225/18|725/9|925/18|between monopoly and triopoly
---